language: node_js
node_js:
  - stable
install:
  - npm install --g lerna
  - npm install
  - lerna bootstrap --hoist
  
script:
  - npm run build
  - npm run test

# Send coverage data to Coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
